spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartai
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: fariddun921uz@gmail.com
    password: kane fdtb mfik bdet
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  security:
    user:
      name: user
      password: user
server:
  port: 8080
